# Generated by Django 3.2.9 on 2021-12-01 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='no lokalu')),
                ('building', models.CharField(max_length=10, verbose_name='nr budynku')),
                ('street', models.CharField(max_length=100, verbose_name='ulica')),
                ('city', models.CharField(max_length=50, verbose_name='masto')),
                ('zip_code', models.CharField(max_length=10, verbose_name='kod pocztowy')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='nazwa usługi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='cena')),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='nazwa firmy')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.address', verbose_name='adres')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='numer faktury')),
                ('payment_date', models.DateField(verbose_name='data płatności')),
                ('payment_status', models.BooleanField(verbose_name='status płatności')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.issuer', verbose_name='sprzedawca')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.service', verbose_name='usługa')),
            ],
        ),
    ]
